// Configuration DNS récursif pour AS5
options {
    directory "/var/cache/bind";
    recursion yes;
    allow-recursion { 120.0.80.0/20; 192.168.5.0/24; };
    listen-on port 53 { 120.0.85.10; any; };
    listen-on-v6 { none; };
    forwarders {
        8.8.8.8;
        8.8.4.4;
    };
    forward only;
    dnssec-validation auto;
    auth-nxdomain no;
};

logging {
    channel default_log {
        file "/var/log/named.log" versions 3 size 5m;
        severity dynamic;
        print-time yes;
    };
    category default { default_log; };
    category queries { default_log; };
};

