client
dev tun
proto udp
remote 120.0.84.14 1194
resolv-retry infinite
nobind
persist-key
persist-tun

ca /tmp/ca.crt
cert /tmp/client.crt
key /tmp/client.key
tls-auth /tmp/ta.key 1
key-direction 1

cipher AES-256-CBC
auth SHA256
comp-lzo
verb 3

