[options]
verbose = 3
debug = 3
alwaysfork = yes
nofork = no
quiet = no
timestamp = yes
execincludes = yes
console = yes
highpriority = yes
initcrypto = yes
nocolor = no
dontwarn = no
dumpcore = no
languageprefix = yes
systemname = asterisk-entreprise5

[directories]
astetcdir => /etc/asterisk
astmoddir => /usr/lib/asterisk/modules
astvarlibdir => /var/lib/asterisk
astdbdir => /var/lib/asterisk
astkeydir => /var/lib/asterisk
astdatadir => /var/lib/asterisk
astagidir => /var/lib/asterisk/agi-bin
astspooldir => /var/spool/asterisk
astrundir => /var/run/asterisk
astlogdir => /var/log/asterisk
astsbindir => /usr/sbin

[files]
astctlpermissions = 0660
astctlowner = root
astctlgroup = asterisk
astctl = asterisk.ctl

[compat]
pbx_realtime = 1.6
res_agi = 1.6

