frr version 9.1
frr defaults traditional
hostname as5-internal
log syslog informational
service integrated-vtysh-config
!
! Interface vers backbone AS5
interface eth0
 ip address 120.0.80.2/24
 ip ospf network point-to-point
!
! Interface vers services AS5
interface eth1
 ip address 120.0.85.1/24
 ip ospf network point-to-point
!
! OSPF Configuration
router ospf
 ospf router-id 120.0.80.2
 network 120.0.80.0/24 area 0
 network 120.0.85.0/24 area 0
 redistribute connected
!
! BGP Configuration
router bgp 5
 bgp router-id 120.0.80.2
 no bgp default ipv4-unicast
 neighbor 120.0.80.1 remote-as 5
 neighbor 120.0.80.1 description AS5 Border Router
 !
 address-family ipv4
  network 120.0.85.0/24
  neighbor 120.0.80.1 activate
  neighbor 120.0.80.1 next-hop-self
 exit-address-family
!
line vty
!

