# Configuration clients FreeRADIUS pour entreprise5
# Format: client <nom> { secret = <secret>; ipaddr = <ip>; }

client localhost {
    ipaddr = 127.0.0.1
    secret = testing123
    require_message_authenticator = no
    nas_type = other
}

client 120.0.84.0/24 {
    secret = radius_secret_entreprise5
    require_message_authenticator = no
    nas_type = other
}

