[general]
static = yes
writeprotect = no
autofallthrough = yes
clearglobalvars = no
priorityjumping = no

[globals]
CONSOLE = Console/dsp
IAXINFO = guest
TRUNK = Zap/g2

[default]
exten => 1001,1,Dial(SIP/1001,20)
exten => 1001,2,Voicemail(1001@default,u)
exten => 1001,3,Hangup()

exten => 1002,1,Dial(SIP/1002,20)
exten => 1002,2,Voicemail(1002@default,u)
exten => 1002,3,Hangup()

exten => _X.,1,Goto(internal,${EXTEN},1)

[internal]
exten => 1001,1,Dial(SIP/1001,20)
exten => 1001,2,Voicemail(1001@default,u)
exten => 1001,3,Hangup()

exten => 1002,1,Dial(SIP/1002,20)
exten => 1002,2,Voicemail(1002@default,u)
exten => 1002,3,Hangup()

exten => _X.,1,Playback(invalid)
exten => _X.,2,Hangup()

[from-external]
exten => _X.,1,Goto(internal,${EXTEN},1)

